### ISSUE TITLE
Cannot destructure property `code` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Alan52** [gxchain/GScatter#13]
描述
GXChain Testnet,  https://testnet.gxchain.org
PC GXCWallet 插件，调用合约报错：
Cannot destructure property `code` of 'undefined' or 'null'.

步骤：
应用调用合约，未唤起插件，即报出以上异常，偶现，频率4/10。

GXCWallet 版本： 0.0.2
合约 gametest2

**Comment by Alan52** [comment]
type: "un_def_error", message: "Cannot destructure property `code` of 'undefined' or 'null'.", code: 433, isError: true, originalError: TypeError: Cannot destructure property `code` of 'undefined' or 'null'.

**Comment by xzshinan** [comment]
方便提供下出现上述情况的 合约的方法，以及 参数 么？

**Comment by lanhaoxiang** [comment]
Will look into this issue in this week

**Comment by Alan52** [comment]
> 以及 参数 么？

method : gamebet(uint64_t game_id, uint8_t bet_type)
param:
game_id : current game id 
bet_type: [1- 4]

**Comment by Alan52** [comment]
> 方便提供下出现上述情况的 合约的方法，以及 参数 么？
