### ISSUE TITLE
类似于消息签名的功能，来验证用户的权限

### ISSUE THREAD

**Issue by chenluyong** [gxchain/GScatter#3]
# 现状
目前`scatter`在登录方面，大多数入口都会放宽要求，不会要求用户输入密码，这已经是常态。
我相信这也将会是 `GScatter` 未来的常态，虽然现在已经如此了。

# 未来
基于这样的应用场景，更需要一个类似于消息签名的功能，来满足DAPP检验使用者是否真实的持有私钥。
以保证进入的用户拥有足够的权限。

**Comment by DophinL** [comment]
close 77b96f9d343975e7ef9eeab063fc3f66f65138ad

文档见这里 https://github.com/gxchain/gscatter-js/blob/master/README-cn.md#%E7%AD%BE%E5%90%8D
