### ISSUE TITLE
Design flaws in the voting function

### ISSUE THREAD

**Issue by chenluyong** [gxchain/GScatter#7]
**Describe the bug**

An incomprehensible voting feature design

**To Reproduce**

1. Use GScatter

2. Select the public chain node of `zhuliting`
    ![image](https://user-images.githubusercontent.com/19658298/57371599-b757ee80-71c5-11e9-96ae-6dd1be13d01a.png)

3. initiate a vote

    ![image](https://user-images.githubusercontent.com/19658298/57371605-bc1ca280-71c5-11e9-96c5-af9a8dabb1d0.png)

**Expected behavior**

The only election  `zhuliting`

**Additional context**

network:  TestNet
account: `panxiaoqin3`

**Your GXChain Account**

my account name is [`louie`](https://block.gxb.io/#/account/louie)

**Comment by lanhaoxiang** [comment]
This is a special consideration for voting function, see comments in https://github.com/gxchain/gxclient-node/blob/master/lib/src/GXClient.js#L648

**Comment by chenluyong** [comment]
关于GScatter的投票功能。
当我调用投票功能，仅传入一个节点名称。GScatter构造了一笔交易，交易中含有历史投票的节点对象。
例：
我第一次投票给A、B。GScatter构造了一笔关于A、B的投票交易。
第二次我仅选择C进行投票，GScatter构造了一笔关于A、B、C的投票交易。

我个人认为，在我进行第二次投票时，我的操作行为会让我的票选投给C节点。
事实与我的预期相悖，这是设计如此还是BUG？

**Comment by chenluyong** [comment]
> This is a special consideration for voting function, see comments in https://github.com/gxchain/gxclient-node/blob/master/lib/src/GXClient.js#L648

` GScatter ` how to do cancel the vote.

**Comment by chenluyong** [comment]
`GScatter` The view displays one node, but more than one node is actually invested. Is it consistent with the original design intention?

**Comment by lanhaoxiang** [comment]
> > This is a special consideration for voting function, see comments in https://github.com/gxchain/gxclient-node/blob/master/lib/src/GXClient.js#L648
> 
> `GScatter` how to do cancel the vote.

Not designed yet, considering overwrite will happen when user visit different site and voting for them, maybe we need a append flag in the api

**Comment by chenluyong** [comment]
it should address the display errors on the view, if the design is like this.

**Comment by lanhaoxiang** [comment]
> it should address the display errors on the view, if the design is like this.

Good suggestion and PR is also welcome, best solution looks like this: Display all voted accounts in the panel with checkbox(es), and the user can determine by check or uncheck the accounts they originally voted before he/she click on the confirm button

**Comment by chenluyong** [comment]
`GScatter` 的定位应该是交易签名、私钥管理的载体，而不是执行业务逻辑的终端。
应该尝试把业务交给使用 `GScatter` 的应用程序，而不是试图代替终端应用程序。

------

` GScatter ` positioning should be trading the signature, the carrier of private key management, rather than execute the business logic of the terminal.
Should try to give the business to use ` GScatter ` applications, rather than trying to replace them.

**Comment by chenluyong** [comment]
> > it should address the display errors on the view, if the design is like this.
> 
> Good suggestion and PR is also welcome, best solution looks like this: Display all voted accounts in the panel with checkbox(es), and the user can determine by check or uncheck the accounts they originally voted before he/she click on the confirm button

这个看起来是解决了当前遇到的操作与行为不统一的问题，即现在是界面显示与链上交易一致。

但是在唤起`GScatter`投票确认页面之前，发起这笔交易的终端已经做出了合适的选择。
`GScatter`为什么要画蛇添足试图修改原本的执行逻辑呢？

--------

This seems to solve the current problem of inconsistent operation and behavior, that is, the interface display is now consistent with transactions on the chain.

But in arousing ` GScatter ` vote confirmation page before launch the terminal of this deal has made the right choice.
Why ` GScatter ` gild the lily tried to modify the original execution logic?

**Comment by lanhaoxiang** [comment]
> > > it should address the display errors on the view, if the design is like this.
> > 
> > 
> > Good suggestion and PR is also welcome, best solution looks like this: Display all voted accounts in the panel with checkbox(es), and the user can determine by check or uncheck the accounts they originally voted before he/she click on the confirm button
> 
> 这个看起来是解决了当前遇到的操作与行为不统一的问题，即现在是界面显示与链上交易一致。
> 
> 但是在唤起`GScatter`投票确认页面之前，发起这笔交易的终端已经做出了合适的选择。
> `GScatter`为什么要画蛇添足试图修改原本的执行逻辑呢？
> 
> This seems to solve the current problem of inconsistent operation and behavior, that is, the interface display is now consistent with transactions on the chain.
> 
> But in arousing `GScatter` vote confirmation page before launch the terminal of this deal has made the right choice.
> Why `GScatter` gild the lily tried to modify the original execution logic?

You are right, but we still need to display what action looks like before the user click on the confirm button, they would not able to check or uncheck current selections

**Comment by chenluyong** [comment]
> > > > it should address the display errors on the view, if the design is like this.
> > > 
> > > 
> > > Good suggestion and PR is also welcome, best solution looks like this: Display all voted accounts in the panel with checkbox(es), and the user can determine by check or uncheck the accounts they originally voted before he/she click on the confirm button
> > 
> > 
> > 这个看起来是解决了当前遇到的操作与行为不统一的问题，即现在是界面显示与链上交易一致。
> > 但是在唤起`GScatter`投票确认页面之前，发起这笔交易的终端已经做出了合适的选择。
> > `GScatter`为什么要画蛇添足试图修改原本的执行逻辑呢？
> > This seems to solve the current problem of inconsistent operation and behavior, that is, the interface display is now consistent with transactions on the chain.
> > But in arousing `GScatter` vote confirmation page before launch the terminal of this deal has made the right choice.
> > Why `GScatter` gild the lily tried to modify the original execution logic?
> 
> You are right, but we still need to display what action looks like before the user click on the confirm button, they would not able to check or uncheck current selections

我认同您关于对已构建的交易进行二次编辑的行为。支持更丰富的选择，看起来是一种合适的优化。
个人建议不要主动添加历史投票信息，除非用户想这样，否则不要帮用户做出判断。

------

I agree with you that a second edit of the built transaction to support a richer selection seems like an appropriate optimization.
Personally, I suggest that you should not actively add historical voting information. Unless users want to, you should not help users make judgments.

**Comment by lanhaoxiang** [comment]
Here is my suggestions:

1. Add `append` options(defaults to true, so it's compatible with old version) to gxclient vote action, it will looks like
```js
vote(accounts = [], broadcast = false, options = {append:true})
```

2. Display the `append` flag in `GScatter` confirm panel, alert the user if the action will overwrite voting targets (append = false)

**Comment by chenluyong** [comment]
> Here is my suggestions:
> 
> 1. Add `append` options(defaults to true, so it's compatible with old version) to gxclient vote action, it will looks like
> 
> ```js
> vote(accounts = [], broadcast = false, options = {append:true})
> ```
> 
> 1. Display the `append` flag in `GScatter` confirm panel, alert the user if the action will overwrite voting targets (append = false)

good job!

**Comment by lanhaoxiang** [comment]
fixed by https://github.com/gxchain/GScatter/pull/12
